mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)

  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    cache-enabled: false
    call-setters-on-nulls: true # true 当查询结果字段值为空时，也返回此字段； false 不返回此字段

server:
  port: 8080
  servlet:
    context-path: /application

javamelody:
  # JavaMelody的初始化参数（可选）
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    charset: UTF-8
    # 记录http请求
    log: true
    # 从监视中排除图像，css，字体和js网址
    url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/js/.*)
    # 添加基本身份验证
    authorized-users: admin:123qwe
    # 更改默认存储目录：
    storage-directory: /tmp/javamelody
    # 更改默认的“ / monitoring”路径：
    monitoring-path: /doufu-wanzi/console/admin

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.21.251:3306/wanzi?useUnicode=true&useSSL=false&characterEncoding=utf8
    druid:
      username: doufu
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  redis:
    host: 39.106.21.251
    port: 6379
    password: 123456
    timeout: 10000ms