mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)

  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    cache-enabled: false
    call-setters-on-nulls: true # true 当查询结果字段值为空时，也返回此字段； false 不返回此字段

server:
  port: 80
  servlet:
    context-path: /doufu-wanzi

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.152.129:3306/sqlserver?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: sqlserver
    password: doufuwanzi
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

  redis:
    database: 0  #Redis数据库索引（默认为0）
    host: 43.143.152.129
    port: 6379 #Redis服务器连接端口
    timeout: 5000MS  # 连接超时时间 单位 ms（毫秒）
    jedis:
      pool:
        min-idle: 10
        max-idle: 20
        max-wait: -1ms
        max-active: 200