mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)

  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    cache-enabled: false
    call-setters-on-nulls: true # true 当查询结果字段值为空时，也返回此字段； false 不返回此字段

server:
  port: 8080

javamelody:
  # JavaMelody的初始化参数（可选）
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    charset: UTF-8
    # 记录http请求
    log: true
    # 从监视中排除图像，css，字体和js网址
    url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/js/.*)
    # 添加基本身份验证
    authorized-users: admin:123qwe
    # 更改默认存储目录：
    storage-directory: /tmp/javamelody
    # 更改默认的“ / monitoring”路径：
    monitoring-path: /doufu-wanzi/console/admin

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.103.254:3306/doufu?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: user
    password: 123456
  data:
    redis:
      host: 47.94.103.254
      port: 6379
      timeout: 10000ms